export function getWelcomeMd(): string {
  const today = new Date().toISOString().slice(0, 10);
  return [
    "---",
    "title: Welcome to NoteBuddy",
    "type: source",
    "tags: [welcome, getting-started]",
    `created: ${today}`,
    `updated: ${today}`,
    "---",
    "",
    "# Welcome to NoteBuddy ✦",
    "",
    "A fast, local-first markdown editor built with Tauri + Rust + React. Your notes live on your machine — no cloud, no accounts.",
    "",
    "## Getting started",
    "",
    "Open or create a `.md` file to start writing. The editor and live preview sit side-by-side. Drag the divider to resize.",
    "",
    "## Writing markdown",
    "",
    "```markdown",
    "# Heading 1",
    "## Heading 2",
    "",
    "**bold**, *italic*, ~~strikethrough~~",
    "",
    "- bullet list",
    "1. numbered list",
    "- [ ] task item",
    "",
    "> blockquote",
    "",
    "[link text](https://example.com)",
    "![image alt](./image.png)",
    "```",
    "",
    "## Wikilinks",
    "",
    "Link between notes using `[[Note Name]]` syntax — click the link in the preview to open that note:",
    "",
    "```markdown",
    "See also [[My Other Note]] for more details.",
    "```",
    "",
    "## Code blocks",
    "",
    "Fenced code blocks get syntax highlighting in the preview and full language-aware autocomplete in the editor. Works for TypeScript, Python, Rust, Go, Java, C++, SQL, Bash and more:",
    "",
    "```typescript",
    "function greet(name: string): string {",
    "  return `Hello, ${name}!`;",
    "}",
    "```",
    "",
    "```rust",
    "fn main() {",
    '    println!("Hello from Rust!");',
    "}",
    "```",
    "",
    "## Mermaid diagrams",
    "",
    "```mermaid",
    "graph TD",
    "  A[Open note] --> B{Has frontmatter?}",
    "  B -->|Yes| C[Show metadata bar]",
    "  B -->|No| D[Plain preview]",
    "```",
    "",
    "## Math / LaTeX",
    "",
    "Inline math: $E = mc^2$",
    "",
    "Display math:",
    "",
    "$$",
    "\\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}",
    "$$",
    "",
    "## Frontmatter",
    "",
    "Every note can have a YAML frontmatter block. It renders as a metadata bar above the preview, with clickable tag chips that filter the file tree:",
    "",
    "```yaml",
    "---",
    "title: My Note",
    "type: concept",
    "tags: [rust, programming]",
    "created: 2026-01-01",
    "---",
    "```",
    "",
    "**Types:** `source` · `concept` · `entity` · `topic`",
    "",
    "## Emoji autocomplete",
    "",
    "Type `:` anywhere to trigger emoji autocomplete — `:smile` → 😄, `:rocket` → 🚀",
    "",
    "## Slash commands",
    "",
    "Type `/` at the start of a line to insert common blocks: headings, callouts, tables, ToC, mermaid, frontmatter, and more.",
    "",
    "## Image paste",
    "",
    "Paste or drag an image into the editor — it's saved to `assets/` automatically and the markdown link is inserted for you.",
    "",
    "## Keyboard shortcuts",
    "",
    "| Shortcut | Action |",
    "| --- | --- |",
    "| `⌘S` | Save file |",
    "| `⌘K` | Command palette (search + commands) |",
    "| `⌘F` | Find & replace |",
    "| `⌘P` | Print / Export as PDF |",
    "| `Ctrl+Space` | Trigger autocomplete |",
    "| `Tab` | Accept autocomplete suggestion |",
    "| `Esc` | Dismiss autocomplete / find panel |",
    "",
    "## Command palette ⌘K",
    "",
    "Press `⌘K` to open the command palette:",
    "",
    "- **Type anything** to full-text search across all notes in your folder",
    "- **Type `>`** to filter commands: new file, save, switch view, export HTML, export PDF, settings",
    "",
    "## Tips",
    "",
    "- **Sidebar** — hover any file or folder to see rename/delete buttons; right-click for a context menu",
    "- **Tag filtering** — click a tag chip in the preview bar or sidebar to filter the file tree",
    "- **Split view** — drag the divider between editor and preview to resize panes",
    "- **Settings ⚙** — change editor/preview themes, font size, window opacity, vibrancy, auto-save",
    "- **Export** — `⌘K` → `> export html` or `> export pdf` to save your note",
    "- **Wikilinks** — `[[Note Name]]` creates clickable links between notes",
    "- **Recent files** — tracked automatically, accessible via the command palette",
    "",
    "Happy writing! ✦",
  ].join("\n");
}
